# Development version of docker compose
include:
  - docker-compose.loki.yml

services:
  dev:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ./:/node
      - client_node_modules:/node/client/node_modules

  client:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: client-dev
    ports:
      - 9000:5173
    volumes:
      - ./:/node
      - client_node_modules:/node/client/node_modules

  storybook:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: client-dev
    ports:
      - 9001:9001
    command: npm run storybook:docker
    volumes:
      - ./:/node
      - client_node_modules:/node/client/node_modules

  storybook-build:
    profiles:
      - "explicit-only"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: client-dev
    command: npm run build-storybook
    volumes:
      - ./:/node
      - client_node_modules:/node/client/node_modules

volumes:
  client_node_modules:
