# Development version of docker compose
services:
  dev:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ./:/node
      - client_node_modules:/node/client/node_modules

  client:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: client-dev
    ports:
      - 9000:5173
    volumes:
      - ./:/node
      - client_node_modules:/node/client/node_modules

  storybook:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: client-dev
    ports:
      - 9001:9001
    command: npm run storybook:docker
    volumes:
      - ./:/node
      - client_node_modules:/node/client/node_modules

  storybook-build:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: client-dev
    command: npm run build-storybook
    volumes:
      - ./:/node
      - client_node_modules:/node/client/node_modules

  loki:
    build:
      context: ./client
      dockerfile: ../Dockerfile.loki
      target: loki
    volumes:
      - ./client/storybook-static:/app/storybook-static
      - ./client/.loki:/app/.loki
    environment:
      STORYBOOK_URI: --reactUri file:./storybook-static
    # command: tail -f /dev/null
    command: npx loki test --verboseRenderer --chromeRetries 3 --requireReference ${STORYBOOK_URI} ${LOKI_CHROME_FLAG}

volumes:
  client_node_modules:
